services:
  api:
    container_name: travel_test_api
    environment: 
      - PGUSER=traveladmin
      - PGHOST=db
      - PGPASSWORD=travelpass
      - PGDATABASE=travel_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: travel_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=travel_test
      - POSTGRES_PASSWORD=travelpass
volumes:
  test_db:
networks: 
  default:
    name: travel_test