services:
  api:
    container_name: travel_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=traveladmin
      - PGHOST=db
      - PGPASSWORD=travelpass
      - PGDATABASE=travel
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: travel_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=travel
      - POSTGRES_USER=traveladmin
      - POSTGRES_PASSWORD=travelpass
volumes:
  dbdata:
networks: 
  default:
    name: travel_api